development:
  :logfile: ./log/sidekiq_development.log
  :verbose: true
  :pidfile: ./log/tmp/pids/sidekiq.pid
  :concurrency: 10
  :queues:
    - [default , 7]
    - [DelayedMailer , 5]
production:
  :concurrency: 20
  